def showMenu():
    print('='*60)
    print('\t\tARITHMETIC OPERATIONS')
    print('='*60)
    print('\t1.Addition')
    print('\t2.Subtraction')
    print('\t3.Multiplication')
    print('\t4.Normal Division')
    print('\t5.Floor Division')
    print('\t6.Modulo Division')
    print('\t7.Exponention')
    print('\t8.Exit')