a=int(input("Enter the first number : "))
b=int(input("Enter the secound number : "))
print("-"*20,"\nRelational Operators\n","-"*20)
print("{}>{} : {}".format(a,b,(a>b)))
print("{}<{} : {}".format(a,b,(a<b)))
print("{}=={} : {}".format(a,b,(a==b)))
print("{}!={} : {}".format(a,b,(a!=b)))
print("{}>={} : {}".format(a,b,(a>=b)))
print("{}<={} : {}".format(a,b,(a<=b)))